spring:
  cloud:
    config:
      enabled: false
      override-system-properties: false
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: employee-service
          uri: lb:http://EMPLOYEE-SERVICE
          predicates:
            - Path=/v1/employees/**, /v1/department/**, /v1/teams/**
        - id: award-service
          uri: lb:http://AWARD-SERVICE
          predicates:
            - Path=/v1/award/**
        - id: goody-service
          uri: lb:http://GOODY-SERVICE
          predicates:
            - Path=/v1/goody/**

server:
  port: 8222