spring:
  config:
    activate:
      on-profile: demo

  cloud:
    config:
      server:
        git:
          uri: ""
        native:
          search-locations: classpath:/config

server:
  port: "${CONFIG_SERVER_PORT}"